apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts: # pod path
        - name: myvolume
          mountPath: /usr/share/nginx/html
      volumes: # work node path 
      - name: myvolume
        hostpath: 
          path: /home/ubuntu/bkp # created inside EBS of worker node 
          type: DirectoryOrCreate
 